server:
  port: 80

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://mytestdb.cmwq7didtr7s.ap-northeast-2.rds.amazonaws.com/postgres
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true